/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'fluent:book-information-24-regular',
      order: 99
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'monitor',
    path: '/monitor',
    component: 'layout.base',
    meta: {
      title: 'monitor',
      i18nKey: 'route.monitor'
    },
    children: [
      {
        name: 'monitor_cache',
        path: '/monitor/cache',
        component: 'view.monitor_cache',
        meta: {
          title: 'monitor_cache',
          i18nKey: 'route.monitor_cache'
        }
      },
      {
        name: 'monitor_logininfor',
        path: '/monitor/logininfor',
        component: 'view.monitor_logininfor',
        meta: {
          title: 'monitor_logininfor',
          i18nKey: 'route.monitor_logininfor'
        }
      },
      {
        name: 'monitor_online',
        path: '/monitor/online',
        component: 'view.monitor_online',
        meta: {
          title: 'monitor_online',
          i18nKey: 'route.monitor_online'
        }
      },
      {
        name: 'monitor_operlog',
        path: '/monitor/operlog',
        component: 'view.monitor_operlog',
        meta: {
          title: 'monitor_operlog',
          i18nKey: 'route.monitor_operlog'
        }
      }
    ]
  },
  {
    name: 'project',
    path: '/project',
    component: 'layout.base',
    meta: {
      title: 'project',
      i18nKey: 'route.project'
    },
    children: [
      {
        name: 'project_product-config',
        path: '/project/product-config',
        component: 'view.project_product-config',
        meta: {
          title: 'project_product-config',
          i18nKey: 'route.project_product-config'
        }
      },
      {
        name: 'project_qc-standard',
        path: '/project/qc-standard',
        component: 'view.project_qc-standard',
        meta: {
          title: 'project_qc-standard',
          i18nKey: 'route.project_qc-standard'
        }
      },
      {
        name: 'project_quality',
        path: '/project/quality',
        meta: {
          title: 'project_quality',
          i18nKey: 'route.project_quality'
        },
        children: [
          {
            name: 'project_quality_bioinfo',
            path: '/project/quality/bioinfo',
            component: 'view.project_quality_bioinfo',
            meta: {
              title: 'project_quality_bioinfo',
              i18nKey: 'route.project_quality_bioinfo'
            }
          },
          {
            name: 'project_quality_wet-lab',
            path: '/project/quality/wet-lab',
            component: 'view.project_quality_wet-lab',
            meta: {
              title: 'project_quality_wet-lab',
              i18nKey: 'route.project_quality_wet-lab'
            }
          }
        ]
      }
    ]
  },
  {
    name: 'social-callback',
    path: '/social-callback',
    component: 'layout.blank$view.social-callback',
    meta: {
      title: 'social-callback',
      i18nKey: 'route.social-callback',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      localIcon: 'menu-system',
      order: 1
    },
    children: [
      {
        name: 'system_client',
        path: '/system/client',
        component: 'view.system_client',
        meta: {
          title: 'system_client',
          i18nKey: 'route.system_client'
        }
      },
      {
        name: 'system_config',
        path: '/system/config',
        component: 'view.system_config',
        meta: {
          title: 'system_config',
          i18nKey: 'route.system_config'
        }
      },
      {
        name: 'system_dict',
        path: '/system/dict',
        component: 'view.system_dict',
        meta: {
          title: 'system_dict',
          i18nKey: 'route.system_dict'
        }
      },
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu',
          i18nKey: 'route.system_menu',
          localIcon: 'menu-tree-table',
          order: 3
        }
      },
      {
        name: 'system_notice',
        path: '/system/notice',
        component: 'view.system_notice',
        meta: {
          title: 'system_notice',
          i18nKey: 'route.system_notice'
        }
      },
      {
        name: 'system_oss',
        path: '/system/oss',
        component: 'view.system_oss',
        meta: {
          title: 'system_oss',
          i18nKey: 'route.system_oss'
        }
      },
      {
        name: 'system_oss-config',
        path: '/system/oss-config',
        component: 'view.system_oss-config',
        meta: {
          title: 'system_oss-config',
          i18nKey: 'route.system_oss-config',
          constant: true,
          hideInMenu: true,
          icon: 'hugeicons:configuration-01'
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role'
        }
      },
      {
        name: 'system_tenant',
        path: '/system/tenant',
        component: 'view.system_tenant',
        meta: {
          title: 'system_tenant',
          i18nKey: 'route.system_tenant'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user'
        }
      }
    ]
  },
  {
    name: 'tool',
    path: '/tool',
    component: 'layout.base',
    meta: {
      title: 'tool',
      i18nKey: 'route.tool',
      localIcon: 'menu-tool',
      order: 4
    },
    children: [
      {
        name: 'tool_gen',
        path: '/tool/gen',
        component: 'view.tool_gen',
        meta: {
          title: 'tool_gen',
          i18nKey: 'route.tool_gen',
          localIcon: 'menu-code',
          order: 2
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      icon: 'material-symbols:account-circle-full',
      hideInMenu: true
    }
  }
];
